import { expect, test } from '@playwright/test'

test('the published artifact exposes the offline workshop and recent pages', async ({ page, browser }) => {
  const apiRequests: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request.url()) })
  await page.goto('./')
  await expect(page.getByRole('button', { name: 'Choose a deck to begin' })).toBeVisible()
  await page.getByRole('button', { name: /The Pressroom Parade/ }).click()
  await page.getByRole('button', { name: 'Begin offline demo' }).click()
  await expect(page.locator('.offline-banner')).toContainText('Progress is not shared')
  await expect(page.locator('.sidebar nav').getByRole('button', { name: /Commissions/ })).toBeDisabled()
  await expect(page.locator('.sidebar nav').getByRole('button', { name: /Trading Hall/ })).toBeDisabled()

  await page.locator('.sidebar nav').getByRole('link', { name: 'Card Library' }).click()
  await expect(page.locator('.boxed-card')).toHaveCount(6)
  await page.getByRole('group', { name: 'Filter cards by type' }).getByRole('button', { name: /SPELL/ }).click()
  await expect(page.locator('.boxed-card')).toHaveCount(2)
  await expect(page).toHaveURL(/#\/library\/type\/spell$/)
  await page.getByRole('group', { name: 'Filter cards by type' }).getByRole('button', { name: /ALL CARDS/ }).click()
  await page.getByRole('button', { name: /Inspect Apprentice Press Cat/ }).first().click()
  const share = page.getByRole('link', { name: 'Copy public link' })
  await expect(share).toHaveAttribute('href', /#\/card\/snapshot\//)
  const guest = await browser.newContext()
  const shared = await guest.newPage()
  shared.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request.url()) })
  await shared.goto((await share.getAttribute('href'))!)
  await expect(shared.getByRole('heading', { name: 'Apprentice Press Cat', level: 1 })).toBeVisible()
  await expect.poll(() => shared.locator('.public-card-art img.art-base').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0)
  await guest.close()
  await expect(page.getByRole('button', { name: 'All parts learned' })).toBeDisabled()
  await expect(page.locator('.grade-cost-note')).toContainText('Grading costs 1 ink and 1 sleeve')
  await page.getByRole('button', { name: 'Grade & slab' }).click()
  await expect(page.getByRole('button', { name: 'Break slab' })).toBeVisible()
  await page.getByRole('button', { name: 'Close inspection' }).click()

  await page.locator('.sidebar nav').getByRole('link', { name: 'Progress' }).click()
  await expect(page.getByRole('region', { name: 'Borders' })).toBeVisible()
  await expect(page.locator('.progress-resource')).not.toHaveCount(0)
  await page.locator('.sidebar nav').getByRole('link', { name: 'Decks' }).click()
  await expect(page.locator('.deck-box')).toHaveCount(10)
  const starter = page.locator('.deck-box').filter({ hasText: 'The Pressroom Parade' }).first()
  await starter.getByRole('button', { name: 'Claim reward' }).click()
  await expect(starter.getByRole('button', { name: 'Reward claimed' })).toBeDisabled()
  await page.locator('.sidebar nav').getByRole('link', { name: 'Finish Gallery' }).click()
  await expect(page.locator('.finish-option')).toHaveCount(11)
  await page.locator('.sidebar nav').getByRole('link', { name: 'Games' }).click()
  await expect(page.locator('.game-stub')).toHaveCount(4)
  await page.getByRole('button', { name: 'Play ↗' }).first().click()
  await expect(page).toHaveURL(/#\/games\/game\/fishing$/)
  await page.reload()
  await expect(page.getByRole('button', { name: 'All games' })).toBeVisible()
  for (const [index, heading] of [[1, /Paperwork with paws/], [2, /Wait, you can play/], [3, /One more run through the furnace/]] as const) {
    await page.getByRole('button', { name: 'All games' }).click()
    await page.locator('.game-stub').nth(index).getByRole('button', { name: 'Play ↗' }).click()
    await expect(page.getByRole('heading', { name: heading })).toBeVisible()
    if (index === 2) {
      await page.getByRole('button', { name: /Choose 6 from my box/ }).click()
      await page.getByRole('button', { name: 'Play bot' }).click()
      await expect(page.locator('.tcg-own-board .tcg-slot')).toHaveCount(5)
      await page.reload()
      await expect(page.locator('.tcg-opponent-board .tcg-slot')).toHaveCount(5)
    }
  }
  await page.locator('.sidebar nav').getByRole('link', { name: 'Print Sheets' }).click()
  await page.locator('.physical-card-choice').first().getByRole('button', { name: /^Add / }).click()
  await expect(page.locator('.physical-placement')).toHaveCount(1)
  await page.getByLabel('File format').selectOption('png')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Create print files' }).click()
  expect((await download).suggestedFilename()).toBe('tcps-print-sheet.png')
  expect(apiRequests).toEqual([])
})

test('a newly printed demo card remains shareable in the static build', async ({ page, browser }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /The Pressroom Parade/ }).click()
  await page.getByRole('button', { name: 'Begin offline demo' }).click()
  await page.getByRole('textbox', { name: /Title or theme hint/ }).fill('A moonlit paper fox')
  await page.getByRole('button', { name: /Pull the lever & print/ }).click()
  await expect(page.locator('.inspect-info h2')).toHaveText('A moonlit paper fox', { timeout: 20_000 })
  const share = page.getByRole('link', { name: 'Copy public link' })
  await expect(share).toHaveAttribute('href', /#\/card\/snapshot\//)
  const guest = await browser.newContext()
  const shared = await guest.newPage()
  await shared.goto((await share.getAttribute('href'))!)
  await expect(shared.getByRole('heading', { name: 'A moonlit paper fox', level: 1 })).toBeVisible()
  await expect.poll(() => shared.locator('.public-card-art img.art-base').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0)
  await guest.close()
})
