import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './printing.css'
import './finish-gallery.css'
import './collection-progress.css'
import './starter-welcome.css'
import './foil.css'
import './card-flip.css'
import './card-styles.css'
import './card-protection.css'
import './progress-page.css'
import './card-library.css'

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
import './mobile-card.css'
import './demo-nav.css'
import './physical-print.css'
import './public-card.css'
import './games-hub.css'
import './decks-page.css'

import './papermill-game.css'
import './tabletop-game.css'
